export const GET_INITIAL_MOVIES = 'GET_INITIAL_MOVIES';
export const GET_INITIAL_MOVIES_SUCCESS = 'GET_INITIAL_MOVIES_SUCCESS';
export const GET_INITIAL_MOVIES_FAILURE = 'GET_INITIAL_MOVIES_FAILURE';

export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';
